### ISSUE TITLE
Should we support kid guard?

### ISSUE THREAD

**Issue by kevinzhow** [Myoland/VaporScope#1]
By default the signers will match and verify the token by the kid value provided in the token.
But we might facing some use cases that requiring kid guard.

## Signer User
```swift
posts.post(use: create).scope(with: ["posts:create"], by: User.self, kid: "user")
```

## Signer Admin
```swift
posts.delete(use: delete).scope(with: ["posts:admin"], by: User.self, kid: "admin")
```

if we dont check kid

```swift
posts.delete(use: delete).scope(with: ["posts:admin"], by: User.self)
```

The user signer can fake and pass the scope check.

**Comment by AFutureD** [comment]
The signer should be specified by `kid` in header.

See [JWTSigners.swift, line 154](https://github.com/vapor/jwt-kit/blob/main/Sources/JWTKit/JWTSigners.swift)

**Comment by AFutureD** [comment]
In this situation, I'll try to introduce `role` into payload.

**Comment by AFutureD** [comment]
Some References:
1. https://www.iana.org/assignments/jwt/jwt.xhtml
2. https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims

**Comment by AFutureD** [comment]
@kevinzhow 
In v1.0.0, we support a more generic method, this may resolve your problem.

Notice, we have change the package url to https://github.com/Myoland/VaporAuth
